### ISSUE TITLE
I couldn't understand how to use GlycoEnzOnto for enrichment analysis and illustration of glycopathway.

### ISSUE THREAD

**Issue by dogTK** [neel-lab/GlycoEnzOnto#4]
I would like to try glycogene enrichment analysis and llustration of various reaction types by GlycoEnzOnto. But I couldn’t understand the usage regardless of reading README and Published paper. Could you please answer some questions below?

1.  Do we have to prepare how input file(ex. RNA-seq TPM data)? If possible, could you give me a sample file?
2. In which directory should I use what tarminal command?

I would appreciate your response when you are available.

**Comment by tgroth58** [comment]
Hello @dogTK,

With regards to running enrichment analyses, we have included some documentation on how one could run GSEA analysis using GlycoEnzOnto pathways.  You can find this documentation [here](https://github.com/neel-lab/GlycoEnzOnto/enrichment_analysis).  Please reach out if you have any questions about this or if something is unclear.

I'm assuming your second question refers to the glycosylation network generation code.  Could you be more specific as to what kind of trouble you're running into?  Once we get a better idea on this we can then improve the network generation documentation and help you more efficiently.

**Comment by dogTK** [comment]
@tgroth58 
Thank you for your reply! When I checked the link(https://github.com/neel-lab/GlycoEnzOnto/enrichment_analysis), the page showed a 404 error, so I couldn't see it. Could you check the link property I can see?

**Comment by neel-lab** [comment]
Please see: https://github.com/neel-lab/GlycoEnzOnto/tree/main/enrichment_analysis

**Comment by dogTK** [comment]
@neel-lab 
I could check it. Thank you for your cooperation!
I'll try the document. If I couldn't do enrichment analysis, I would ask again. Thanks!
